### ISSUE TITLE
Error when executing `repo --version`

### ISSUE THREAD

**Issue by itsayellow** [grouperenault/gitrepo#5]
Thanks for packaging this. 🙂 

Ubuntu 18.04.5
python 3.6.9
gitrepo >= 2.8.0.post1

When I install every version of gitrepo on pypi back to at least 2.8.0.post1, I get the same error when trying to execute `repo --version`:
```
ubi18:~ repo --version
repo version 2.15.4
       (from setup.py)
       (tracking refs/heads/pypi)
Traceback (most recent call last):
  File "/home/mclapp/.local/bin/repo", line 8, in <module>
    sys.exit(main())
  File "/home/mclapp/.local/pipx/venvs/gitrepo/lib/python3.6/site-packages/repo/main.py", line 644, in main
    return _Main(sys.argv[1:])
  File "/home/mclapp/.local/pipx/venvs/gitrepo/lib/python3.6/site-packages/repo/main.py", line 621, in _Main
    result = run()
  File "/home/mclapp/.local/pipx/venvs/gitrepo/lib/python3.6/site-packages/repo/main.py", line 614, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/home/mclapp/.local/pipx/venvs/gitrepo/lib/python3.6/site-packages/repo/main.py", line 263, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/mclapp/.local/pipx/venvs/gitrepo/lib/python3.6/site-packages/repo/subcmds/version.py", line 45, in Execute
    print('       (%s)' % rp.bare_git.log('-1', '--format=%cD', HEAD))
AttributeError: '_FakeBareGit' object has no attribute 'log'
```

This error does not occur when I download and run the latest version of repo from the official repository.

**Comment by tardyp** [comment]
Thanks for report!

Indeed, I do not test repo --version

This issue is now fixed and published in a .post1 version

**Comment by itsayellow** [comment]
Brilliant!  Thanks for the quick fix!

**Comment by tardyp** [comment]
yeah.. its embarrassing we run 10min of integration tests for this thing, but we don't even test repo --version 
🤦 
![image](https://user-images.githubusercontent.com/109859/123153694-3ec85080-d466-11eb-97ef-5d6c11c343ae.png)
